### ISSUE TITLE
gulp usage feels bad

### ISSUE THREAD

**Issue by timomeh** [sprity/sprity#4] opened 2015-05-20 18:50 UTC
As a gulp user with builds for sass, js, svg-maps, and so on; the `sprity.src()` syntax feels really weird. Also I have a few problems with this.

It doesn't translate 100% into a gulp stream. For example, if I want to build sprites for each subdirectory, I can't do it like the [gulp docs](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md) suggest. The merged streams generate totally wrong sprites and css-files. Because of this flaw I'm unable to use sprity in my projects.

Yeah, there's a split-option, but as a gulp user I should be able to be completely free in my workflow. (Also, the split-option seems to generate strange output, too.) That's the first time I see a module not using the normal stream with `gulp.src()` and I already ran into problems.

Don't get me wrong – I just could use another module. But besides the `sprity.src`, this module feels really solid and I would love to use it in future projects.

So, see it as a suggestion: **In my opinion the gulp.src() syntax would be much better.**

**Comment by aslansky** [comment] 2015-05-20 19:20
Do you want to do something before starting sprity in your task? Just asking because sprity.src uses the same internal mechanism as gulp.src:

in Gulps source code: Gulp.prototype.src = vfs.src;
in sprity's source code: return vfs.src(opts.src)

The syntax is just a little bit different. In sprity the file glob is given via the options object. 

For example:
```
sprity.src({
  src: ['./images/*.png', './pictures/*.jpg']
});
```

The only thing you can't do is use sprity in the middle of a gulp stream (Thats why I was asking). To me it wouldn't make that much sense using sprity in the middle of the task as long as you don't want to do something with the images before generating the sprites (I really can't think of something I would want to do with the images before genrating sprite). You can still use the suggested way from the gulp docs just with a little different syntax:

```
gulp.task('sprites', function() {
   var folders = getFolders(spritesPath);
   var tasks = folders.map(function(folder) {
       return sprity.src({
         src: path.join(spritesPath, folder, '/*.png')
      })
      ...
      .pipe(gulp.dest(spritesPath));
   });
});
```

Keep in mind: If you do that and also let sprity generate the css file, there will be naming collisions of css classes. Thats why there is the split option.

I also have to say that sprity is not a gulp plugin. It is a standalone sprite generator that happens to work quite well with gulp because it uses the same internal streaming mechanism.

**Also, the split-option seems to generate strange output, too.**
What do you mean by that? Could you please give me an example of the strange output? It seems like you found a bug, because sprity should return a stream with the sprites for each folder.

**Comment by timomeh** [comment] 2015-05-20 19:59
Thank you for the quick response!

No, I don't want to use sprity in the middle of the gulp stream – I can't imagine a scenario where this is necessary, too. :D

I wanted to use the merged tasks for each directory, and I used the exact same code you wrote.

```js
gulp.task('sprites', function () {
  var folders = getFolders(spritesPath);
  var tasks = folders.map(function (folder) {
    return sprity.src({
      src: path.join(spritesPath, folder, '/*.png'),
      name: 'sprite-' + folder,
      style: './mypath/_sprite-' + folder + '.scss',
      dimension: [{
        ratio: 1, dpi: 72
      }, {
        ratio: 2, dpi: 144
      }]
    })
    .pipe(gulpif('*.png', gulp.dest('./dist/')))
    .pipe(gulpif('*.scss', gulp.dest('./dist')))
  });
  return merge(tasks);
});
```

I made an example with two directories. Each file is 200x200px.
`test1/a.png`, `test1/b.png`
`test2/a.png`, `test2/b.png`, `test2/c.png`, `test2/d.png`

The generated **sprite-test1.png** looks like this:
![sprite-test1](https://cloud.githubusercontent.com/assets/4227520/7734813/3dde1ca8-ff39-11e4-9e61-d5ad4840a37b.png)

The generated **sprite-test2.png** looks like this:
![sprite-test2](https://cloud.githubusercontent.com/assets/4227520/7734819/4bd52856-ff39-11e4-9f19-fadafe0b2db2.png)

The generated variables in **_sprite-test1.scss** are:
```sass
$test1-a: -0px -0px 208px 208px;
$test2-a: -0px -208px 208px 208px;
$test1-b: -0px -416px 208px 208px;
$test2-b: -0px -624px 208px 208px;
$test2-c: -0px -832px 208px 208px;
$test2-d: -0px -1040px 208px 208px;
```

The generated variables in **_sprite-test2.scss** are:
```sass
$test1-a: -0px -0px 208px 208px;
$test2-a: -0px -208px 208px 208px;
$test1-b: -0px -416px 208px 208px;
$test2-b: -0px -624px 208px 208px;
$test2-c: -0px -832px 208px 208px;
$test2-d: -0px -1040px 208px 208px;
$test1-a: -0px -0px 208px 208px;
$test2-a: -0px -208px 208px 208px;
$test1-b: -0px -416px 208px 208px;
$test2-b: -0px -624px 208px 208px;
$test2-c: -0px -832px 208px 208px;
$test2-d: -0px -1040px 208px 208px;
```

*Note: This is no custom processor template, it's sprity-sass.*

### Regarding the split option

Seems like I wrote the configurations somehow wrong. I tried it just now and it works. Sorry for that! Unfortunately this is no option for me, because I need to separate my sprite images in groups. That's why I tried it with the merged streams.

**Comment by aslansky** [comment] 2015-05-20 20:15
Thats seems wrong to me too. I will have a look into it.

**Comment by timomeh** [comment] 2015-05-20 20:20
One last thing I like to mention: apart from that sprity is great. The build-process is superfast, the downscaling to support retina/nonretina is perfect and it keeps projects clean from `@2x.png` files.

**Comment by jedmao** [comment] 2015-05-21 23:36
Why not just make it a gulp plugin? The CLI can just pipe the options directly to it.

**Comment by loremipson** [comment] 2015-05-30 23:57
The way this works aside from just `gulp.src()` makes it so I can't handle any errors that occur.

I'm in a situation where we might not always use sprites on a project. If we do, I'd love to be able to use sprity. If we don't, then.. that should be fine too.

The problem is if I run the sprite task without any images in the directory, it throws an unhandled error and stops gulp from running entirely. Which I can't really do anything about at the moment, it seems. Any error handling I try to do never triggers, as it all seems to happen inside `sprity.src()`

**Comment by aslansky** [comment] 2015-06-07 13:19
@loremipson In 1.0.4 the error handling with gulp should work better. It now emits an error on the stream. So something like:
```
sprity.src({
  src: './images/*.png'
})
.on('error' function (err) {
  console.log(err);
});
```

should work. Error handling in gulp should than work like with every other plugin. Please leave a comment if you still got problems with that.

**Comment by aslansky** [comment] 2015-07-25 07:41
I close the issues since it seems to be fine now.

**Closed by aslansky** 2015-07-25 07:41 UTC
